version: '2.1'

services:
  nginx:
    build: './nginx'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
  ibeam:
    image: ibeam
    container_name: ibeam-2
    environment:
      - APP_NAME=my-app
    env_file:
      - './env.list'
    ports:
      - '5000:5000'
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
